import { Aboutus, ContactUs, Footer, Hero, Services, WhatSay } from '@/components'
import './globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body>
        <Hero/>
        <Services/>
        {children}
      <Aboutus/>
      <WhatSay/>
      <ContactUs/>
      <Footer/>
      
        </body>
    </html>
  )
}
